In [29]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import os

In [ ]:
master_df = pd.read_csv("medicines_master.csv")

print("Total products:", len(master_df))
print("Unique NPL IDs:", master_df["npl_id"].nunique())

master_df.head()

Total products: 15190
Unique NPL IDs: 15190

,product_name,strength,form,atc_code,active_ingredient_simple,active_ingredient,registration_status,sales_status,human_vet,prescription_status,npl_id
0,Abacavir/Lamivudine Accord,600 mg/300 mg,Filmdragerad tablett,J05AR02,Abakavir + lamivudin,abakavir\nlamivudin,Godkänd,Finns till försäljning,HUM,Receptbelagt,20150416000034
1,Abacavir/Lamivudine Glenmark,600 mg/300 mg,Filmdragerad tablett,J05AR02,Abakavir + lamivudin,abakavirhydrokloridmonohydrat\nlamivudin,Godkänd,Finns till försäljning,HUM,Receptbelagt,20180129000014
2,Abacavir/Lamivudine Medical Valley,600 mg/300 mg,Filmdragerad tablett,J05AR02,Abakavir + lamivudin,abakavirsulfat\nlamivudin,Godkänd,Finns till försäljning,HUM,Receptbelagt,20171222000018
3,Abacavir/Lamivudine Sandoz,600 mg/300 mg,Filmdragerad tablett,J05AR02,Abakavir + lamivudin,abakavirhydrokloridmonohydrat\nlamivudin,Godkänd,Finns till försäljning,HUM,Receptbelagt,20141230000119
4,Abacavir/Lamivudine STADA,600 mg/300 mg,Filmdragerad tablett,J05AR02,Abakavir + lamivudin,abakavir\nlamivudin,Godkänd,Finns till försäljning,HUM,Receptbelagt,20151021000044

In [ ]:
master_df["npl_id"] = (
    master_df["npl_id"]
    .astype(str)
    .str.replace(r"\.0$", "", regex=True)
    .str.strip()
)

master_df[["product_name", "strength", "form", "npl_id"]].head()

,product_name,strength,form,npl_id
0,Abacavir/Lamivudine Accord,600 mg/300 mg,Filmdragerad tablett,20150416000034
1,Abacavir/Lamivudine Glenmark,600 mg/300 mg,Filmdragerad tablett,20180129000014
2,Abacavir/Lamivudine Medical Valley,600 mg/300 mg,Filmdragerad tablett,20171222000018
3,Abacavir/Lamivudine Sandoz,600 mg/300 mg,Filmdragerad tablett,20141230000119
4,Abacavir/Lamivudine STADA,600 mg/300 mg,Filmdragerad tablett,20151021000044

In [ ]:
print(master_df["npl_id"].str.len().value_counts().sort_index())

npl_id
14    15190
Name: count, dtype: int64

In [ ]:
def get_fass_text(npl_id):
    url = f"https://fass.se/health/product/{npl_id}/smpc"

    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(
        url,
        headers=headers,
        timeout=30
    )

    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    text = soup.get_text(
        " ",
        strip=True
    )

    return text

In [ ]:
test_row = master_df.iloc[0]

print("Medicine:", test_row["product_name"])
print("NPL ID:", test_row["npl_id"])

test_text = get_fass_text(test_row["npl_id"])

print("Characters downloaded:", len(test_text))
print(test_text[:1000])

Medicine: Abacavir/Lamivudine Accord
NPL ID: 20150416000034
Characters downloaded: 144582
Abacavir/Lamivudine Accord (Filmdragerad tablett 600 mg/300 mg) • Produktresumé | FASS Vård Tillgänglig läkemedelsinformation i Sverige Kontakta oss FAQ Fass Vård Fass Patient Vård Djur MENY / Läkemedel / Abacavir/Lamivudine Accord, Filmdragerad tablett 600 mg/300 mg / Produktresumé Bild saknas orange, kapselformad, 19,4 mm x 10,4 mm orange, kapselformad, 19,4 mm x 10,4 mm Info om att dela och krossa Accord Healthcare AB Abacavir/Lamivudine Accord, Filmdragerad tablett 600 mg/300 mg Antiviralt medel Bild saknas orange, kapselformad, 19,4 mm x 10,4 mm orange, kapselformad, 19,4 mm x 10,4 mm Info om att dela och krossa Om läkemedlet Recept krävs Ingår i högkostnadsskyddet Läkemedel från Accord Healthcare AB omfattas av Läkemedelsförsäkringen Visa alla Beskrivning Antiviralt medel ATC-kod J05AR02 Utbytbara läkemedel Visa 7 st Substanser i alfabetisk ordning Abakavir Lamivudin Abakavir +1 Abakavir Lamivudin Laddar... Fass Tillgänglig läkemedelsinformation i Sverige. Fass är den huvudsaklig

In [ ]:
def extract_section(text, start_heading, end_heading):
    start = text.find(start_heading)

    if start == -1:
        return None

    end = text.find(end_heading, start + len(start_heading))

    if end == -1:
        return None

    return text[start:end].strip()

In [ ]:
sections = {
    "dosage": (
        "4.2 Dosering och administreringssätt",
        "4.3 Kontraindikationer"
    ),

    "contraindications": (
        "4.3 Kontraindikationer",
        "4.4 Varningar och försiktighet"
    ),

    "warnings": (
        "4.4 Varningar och försiktighet",
        "4.5 Interaktioner med andra läkemedel och övriga interaktioner"
    ),

    "interactions": (
        "4.5 Interaktioner med andra läkemedel och övriga interaktioner",
        "4.6 Fertilitet, graviditet och amning"
    ),

    "pregnancy_breastfeeding": (
        "4.6 Fertilitet, graviditet och amning",
        "4.7 Effekter på förmågan att framföra fordon och använda maskiner"
    ),

    "side_effects": (
        "4.8 Biverkningar",
        "4.9 Överdosering"
    )
}

In [ ]:
test_sections = {}

for section_name, (start, end) in sections.items():

    extracted = extract_section(
        test_text,
        start,
        end
    )

    test_sections[section_name] = extracted

    if extracted:
        print(
            section_name,
            "-> OK | characters:",
            len(extracted)
        )
    else:
        print(section_name, "-> NOT FOUND")

dosage -> OK | characters: 4624
contraindications -> OK | characters: 138
warnings -> OK | characters: 12046
interactions -> OK | characters: 7129
pregnancy_breastfeeding -> OK | characters: 2759
side_effects -> OK | characters: 6941

In [ ]:
print(test_sections["interactions"][:2000])

4.5 Interaktioner med andra läkemedel och övriga interaktioner Abacavir/Lamivudine Accord innehåller abakavir och lamivudin och därför är alla tidigare observerade interaktioner för respektive substans relevanta även för Abacavir/Lamivudine Accord. Kliniska studier har visat att det inte finns några kliniskt relevanta interaktioner mellan abakavir och lamivudin. Abakavir metaboliseras via UDP‑glukuronyltransferas (UGT)‑enzymer och alkoholdehydrogenas; samtidig administrering med inducerare eller hämmare av UGT‑enzymer eller med substanser som elimineras via alkoholdehydrogenas kan påverka exponeringen av abakavir. Lamivudin elimineras renalt. Aktiv renal sekretion av lamivudin i urinen medieras genom organiska katjontransportörer (OCT); samtidig administrering av lamivudin och hämmare av OCT kan öka exponeringen av lamivudin. Abakavir och lamivudin metaboliseras inte till någon betydande grad via P450‑enzymer (såsom CYP 3A4, CYP 2C9 eller CYP 2D6). De inducerar inte heller detta enzymsystem. Lamivudin hämmar inte cytokrom P450-enzym. Abakavir påvisar begränsad potential att hämma metabolismen via CYP3A4. Dessutom har det visats att abakavir i n vitro inte hämmar CYP2C9 eller CYP2D6 enzymer. In vitro -studier har visat att abakavir har potential att hämma cytokrom P450 1A1 (CYP1A1). Således är risken därför liten för interaktioner med antiretrovirala proteashämmare, icke-nukleosider eller andra läkemedel som metaboliseras via de viktigaste P450‑enzymerna Abacavir/Lamivudine Accord ska inte användas tillsammans med andra läkemedel som innehåller lamivudin (se avsnitt 4.4). Listan nedan ska inte ses som fullständig, men är representativ för de studerade klasserna. Visa större Läkemedel efter terapiområde Interaktion Förändring av geometriskt medelvärde (%) (Möjlig mekanism) Rekommendation gällande samtidig administrering ANTIRETROVIRALA LÄKEMEDEL didanosin/abakavir Interaktionen är inte studerad. Ingen dosjustering är nödvändig. Didanosin/lamivudin Interaktionen är int

50-product pilot test করি।

In [ ]:
pilot_df = master_df.head(50).copy()

pilot_results = []
pilot_errors = []

for i, row in pilot_df.iterrows():

    name = row["product_name"]
    npl_id = row["npl_id"]

    try:
        text = get_fass_text(npl_id)

        result = {
            "product_name": name,
            "strength": row["strength"],
            "form": row["form"],
            "atc_code": row["atc_code"],
            "active_ingredient": row["active_ingredient"],
            "prescription_status": row["prescription_status"],
            "npl_id": npl_id,
            "source_url": f"https://fass.se/health/product/{npl_id}/smpc"
        }

        # Extract all FASS sections
        for section_name, (start, end) in sections.items():
            result[section_name] = extract_section(
                text,
                start,
                end
            )

        pilot_results.append(result)

        print(name, "-> OK")

    except Exception as e:
        pilot_errors.append({
            "product_name": name,
            "npl_id": npl_id,
            "error": str(e)
        })

        print(name, "-> ERROR:", e)

    # Avoid sending requests too quickly
    time.sleep(1)

Abacavir/Lamivudine Accord -> OK
Abacavir/Lamivudine Glenmark -> OK
Abacavir/Lamivudine Medical Valley -> OK
Abacavir/Lamivudine Sandoz -> OK
Abacavir/Lamivudine STADA -> OK
Abakavir/Lamivudin Viatris -> OK
ABASAGLAR -> OK
ABASAGLAR KwikPen -> OK
ABASAGLAR Tempo Pen -> OK
Abavalex -> OK
Abavalex -> OK
Abavalex -> OK
Abavalex -> OK
Abavalex -> OK
Abbonate -> OK
Abboticin -> OK
Abboticin -> OK
Abboticin Novum -> OK
Abdomin Citrus -> OK
Abdomin Junior Neutral -> OK
Abdomin Neutral -> OK
Abecma -> OK
Abecol -> OK
Abetip -> OK
Abetip -> OK
Abevmy -> OK
Abilify -> OK
Abilify -> OK
Abilify -> OK
Abilify -> OK
Abilify -> OK
Abilify -> OK
Abilify -> OK
Abilify -> OK
Abilify -> OK
ABILIFY MAINTENA -> OK
ABILIFY MAINTENA -> OK
ABILIFY MAINTENA -> OK
ABILIFY MAINTENA -> OK
ABILIFY MAINTENA -> OK
ABILIFY MAINTENA -> OK
Abirateron Avansor -> OK
Abirateron Devatis -> OK
Abirateron Medical Valley -> OK
Abirateron Sandoz -> OK
Abirateron Teva -> OK
Abiraterone Accord -> OK
Abiraterone Accord -> OK
Abiraterone AshCure -> OK
Abiraterone AshCure -> OK

In [ ]:
pilot_result_df = pd.DataFrame(pilot_results)

print("Attempted:", len(pilot_df))
print("Downloaded:", len(pilot_result_df))
print("Request errors:", len(pilot_errors))

pilot_result_df.head()

Attempted: 50
Downloaded: 50
Request errors: 0

,product_name,strength,form,atc_code,active_ingredient,prescription_status,npl_id,source_url,dosage,contraindications,warnings,interactions,pregnancy_breastfeeding,side_effects
0,Abacavir/Lamivudine Accord,600 mg/300 mg,Filmdragerad tablett,J05AR02,abakavir\nlamivudin,Receptbelagt,20150416000034,https://fass.se/health/product/20150416000034/...,4.2 Dosering och administreringssätt Behandlin...,4.3 Kontraindikationer Överkänslighet mot den ...,4.4 Varningar och försiktighet Varningar och f...,4.5 Interaktioner med andra läkemedel och övri...,"4.6 Fertilitet, graviditet och amning Gravidit...",4.8 Biverkningar Sammanfattning av säkerhetspr...
1,Abacavir/Lamivudine Glenmark,600 mg/300 mg,Filmdragerad tablett,J05AR02,abakavirhydrokloridmonohydrat\nlamivudin,Receptbelagt,20180129000014,https://fass.se/health/product/20180129000014/...,4.2 Dosering och administreringssätt Behandlin...,4.3 Kontraindikationer Överkänslighet mot de a...,4.4 Varningar och försiktighet Varningar och f...,4.5 Interaktioner med andra läkemedel och övri...,"4.6 Fertilitet, graviditet och amning Gravidit...",4.8 Biverkningar Sammanfattning av säkerhetspr...
2,Abacavir/Lamivudine Medical Valley,600 mg/300 mg,Filmdragerad tablett,J05AR02,abakavirsulfat\nlamivudin,Receptbelagt,20171222000018,https://fass.se/health/product/20171222000018/...,4.2 Dosering och administreringssätt Behandlin...,4.3 Kontraindikationer Överkänslighet mot den ...,4.4 Varningar och försiktighet Varningar och f...,4.5 Interaktioner med andra läkemedel och övri...,"4.6 Fertilitet, graviditet och amning Gravidit...",4.8 Biverkningar Sammanfattning av säkerhetspr...
3,Abacavir/Lamivudine Sandoz,600 mg/300 mg,Filmdragerad tablett,J05AR02,abakavirhydrokloridmonohydrat\nlamivudin,Receptbelagt,20141230000119,https://fass.se/health/product/20141230000119/...,4.2 Dosering och administreringssätt Behandlin...,4.3 Kontraindikationer Överkänslighet mot de a...,4.4 Varningar och försiktighet Varningar och f...,4.5 Interaktioner med andra läkemedel och övri...,"4.6 Fertilitet, graviditet och amning Gravidit...",4.8 Biverkningar Sammanfattning av säkerhetspr...
4,Abacavir/Lamivudine STADA,600 mg/300 mg,Filmdragerad tablett,J05AR02,abakavir\nlamivudin,Receptbelagt,20151021000044,https://fass.se/health/product/20151021000044/...,4.2 Dosering och administreringssätt Behandlin...,4.3 Kontraindikationer Överkänslighet mot de a...,4.4 Varningar och försiktighet Varningar och f...,4.5 Interaktioner med andra läkemedel och övri...,"4.6 Fertilitet, graviditet och amning Gravidit...",4.8 Biverkningar Sammanfattning av säkerhetspr...

In [ ]:
section_columns = [
    "dosage",
    "contraindications",
    "warnings",
    "interactions",
    "pregnancy_breastfeeding",
    "side_effects"
]

print("\nMissing sections:")

for col in section_columns:
    missing = pilot_result_df[col].isna().sum()
    print(f"{col}: {missing}")

Missing sections:
dosage: 12
contraindications: 12
warnings: 12
interactions: 12
pregnancy_breastfeeding: 12
side_effects: 12

In [ ]:
complete = (
    pilot_result_df[section_columns]
    .notna()
    .all(axis=1)
)

print("\nComplete products:", complete.sum())
print("Incomplete products:", (~complete).sum())

Complete products: 38
Incomplete products: 12

In [ ]:
pilot_result_df.loc[
    ~complete,
    ["product_name", "strength", "form", "npl_id"] + section_columns
]

,product_name,strength,form,npl_id,dosage,contraindications,warnings,interactions,pregnancy_breastfeeding,side_effects
9,Abavalex,10 mg,Filmdragerad tablett,20240402000039,NaN,NaN,NaN,NaN,NaN,NaN
10,Abavalex,100 mg,Filmdragerad tablett,20240402000077,NaN,NaN,NaN,NaN,NaN,NaN
11,Abavalex,25 mg,Filmdragerad tablett,20240402000046,NaN,NaN,NaN,NaN,NaN,NaN
12,Abavalex,50 mg,Filmdragerad tablett,20240402000053,NaN,NaN,NaN,NaN,NaN,NaN
13,Abavalex,75 mg,Filmdragerad tablett,20240402000060,NaN,NaN,NaN,NaN,NaN,NaN
18,Abdomin Citrus,NaN,Pulver till oral lösning i dospåse,20240318000178,NaN,NaN,NaN,NaN,NaN,NaN
23,Abetip,10 mg,Filmdragerad tablett,20210429000176,NaN,NaN,NaN,NaN,NaN,NaN
24,Abetip,20 mg,Filmdragerad tablett,20210429000183,NaN,NaN,NaN,NaN,NaN,NaN
42,Abirateron Devatis,500 mg,Filmdragerad tablett,20250508000031,NaN,NaN,NaN,NaN,NaN,NaN
45,Abirateron Teva,500 mg,Filmdragerad tablett,20201201000118,NaN,NaN,NaN,NaN,NaN,NaN
48,Abiraterone AshCure,250 mg,Filmdragerad tablett,20231030000065,NaN,NaN,NaN,NaN,NaN,NaN
49,Abiraterone AshCure,500 mg,Filmdragerad tablett,20231030000072,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
failed_npl = "20240402000039"

failed_text = get_fass_text(failed_npl)

print("Characters:", len(failed_text))
print(failed_text[:2000])

Characters: 1689
Abavalex (Filmdragerad tablett 10 mg) • Produktresumé | FASS Vård Tillgänglig läkemedelsinformation i Sverige Kontakta oss FAQ Fass Vård Fass Patient Vård Djur MENY / Läkemedel / Abavalex, Filmdragerad tablett 10 mg / Produktresumé Bild saknas Info om att dela och krossa G.L. Pharma Nordic Abavalex, Filmdragerad tablett 10 mg Tillhandahålls ej Bild saknas Info om att dela och krossa Om läkemedlet Läkemedel från G.L. Pharma Nordic omfattas av Läkemedelsförsäkringen Visa alla ATC-kod N03AX23 Utbytbara läkemedel Ej utbytbar Substans Brivaracetam Laddar... Fass Tillgänglig läkemedelsinformation i Sverige. Fass är den huvudsakliga källan för läkemedelsinformation i Sverige sedan 1966. Fass är en del av Lif – branschorganisationen för de forskande läkemedelsföretagen i Sverige. LinkedIn Följ Fass på Linkedin Versionsnummer 20260820.0856-bde47b434 Kontakta oss Telefon: 08-462 37 00 E-post: info@fass.se Box 17608, 118 92 Stockholm Fler kontaktuppgifter Om webbplatsen Om fass.se Tillgänglighet på fass.se Behandling av personuppgifter Presskontakt Kakor på fass.se Användarvillkor Hantera kakor Hitta snabbt Lagerstatus på apotek Identifiera läkemedel ATC-register Fass FAQ Abavalex Filmdragerad tablett 10 mg Fass-vy Produktresumé Fass-text Bipacksedel Lagerstatus Fass har begränsad information om detta läkemedel. För mer information, kontrollera om det finns hos Läkemedelsverket eller kontakta läkemedelsföretaget. Sök läkemedelsfakta | Läkemedelsverket Information som kompletterar produktresumé och bipacksedel Översikt av läkemedlet Rapportera misstänka biverkningar Förpackningar och pris Läkemedlets innehåll Skyddsåtgärder – hantera läkemedlet säkert Produktresumé Läs upp

In [ ]:
for heading in [
    "4.1",
    "4.2",
    "4.3",
    "4.4",
    "4.5",
    "4.6",
    "4.7",
    "4.8",
    "4.9"
]:
    print(heading, failed_text.find(heading))

4.1 -1
4.2 -1
4.3 -1
4.4 -1
4.5 -1
4.6 -1
4.7 -1
4.8 -1
4.9 -1

In [ ]:
print("Characters:", len(failed_text))
print("\nFIRST 3000 CHARACTERS:\n")
print(failed_text[:3000])

Characters: 1689

FIRST 3000 CHARACTERS:

Abavalex (Filmdragerad tablett 10 mg) • Produktresumé | FASS Vård Tillgänglig läkemedelsinformation i Sverige Kontakta oss FAQ Fass Vård Fass Patient Vård Djur MENY / Läkemedel / Abavalex, Filmdragerad tablett 10 mg / Produktresumé Bild saknas Info om att dela och krossa G.L. Pharma Nordic Abavalex, Filmdragerad tablett 10 mg Tillhandahålls ej Bild saknas Info om att dela och krossa Om läkemedlet Läkemedel från G.L. Pharma Nordic omfattas av Läkemedelsförsäkringen Visa alla ATC-kod N03AX23 Utbytbara läkemedel Ej utbytbar Substans Brivaracetam Laddar... Fass Tillgänglig läkemedelsinformation i Sverige. Fass är den huvudsakliga källan för läkemedelsinformation i Sverige sedan 1966. Fass är en del av Lif – branschorganisationen för de forskande läkemedelsföretagen i Sverige. LinkedIn Följ Fass på Linkedin Versionsnummer 20260820.0856-bde47b434 Kontakta oss Telefon: 08-462 37 00 E-post: info@fass.se Box 17608, 118 92 Stockholm Fler kontaktuppgifter Om webbplatsen Om fass.se Tillgänglighet på fass.se Behandling av personuppgifter Presskontakt Kakor på fass.se Användarvillkor Hantera kakor Hitta snabbt Lagerstatus på apotek Identifiera läkemedel ATC-register Fass FAQ Abavalex Filmdragerad tablett 10 mg Fass-vy Produktresumé Fass-text Bipacksedel Lagerstatus Fass har begränsad information om detta läkemedel. För mer information, kontrollera om det finns hos Läkemedelsverket eller kontakta läkemedelsföretaget. Sök läkemedelsfakta | Läkemedelsverket Information som kompletterar produktresumé och bipacksedel Översikt av läkemedlet Rapportera misstänka biverkningar Förpackningar och pris Läkemedlets innehåll Skyddsåtgärder – hantera läkemedlet säkert Produktresumé Läs upp

In [ ]:
keywords = [
    "Produktresumé",
    "Fass-text",
    "Abavalex",
    "Laddar",
    "Dosering",
    "Kontraindikationer",
    "Interaktioner"
]

for word in keywords:
    print(word, "->", failed_text.find(word))

Produktresumé -> 40
Fass-text -> 1238
Abavalex -> 0
Laddar -> 549
Dosering -> -1
Kontraindikationer -> -1
Interaktioner -> -1

In [ ]:
def get_fass_status(text):
    if "Fass har begränsad information om detta läkemedel" in text:
        return "limited_information"

    if "4.2 Dosering och administreringssätt" in text:
        return "smpc_available"

    return "unknown"

In [ ]:
print("Abacavir:", get_fass_status(test_text))
print("Abavalex:", get_fass_status(failed_text))

Abacavir: smpc_available
Abavalex: limited_information

In [ ]:
incomplete_df = pilot_result_df.loc[
    ~complete,
    ["product_name", "npl_id"]
].copy()

status_results = []

for _, row in incomplete_df.iterrows():
    try:
        text = get_fass_text(row["npl_id"])

        status_results.append({
            "product_name": row["product_name"],
            "npl_id": row["npl_id"],
            "fass_status": get_fass_status(text)
        })

        time.sleep(1)

    except Exception as e:
        status_results.append({
            "product_name": row["product_name"],
            "npl_id": row["npl_id"],
            "fass_status": "request_error"
        })

status_df = pd.DataFrame(status_results)

status_df

           product_name          npl_id          fass_status
0              Abavalex  20240402000039  limited_information
1              Abavalex  20240402000077  limited_information
2              Abavalex  20240402000046  limited_information
3              Abavalex  20240402000053  limited_information
4              Abavalex  20240402000060  limited_information
5        Abdomin Citrus  20240318000178  limited_information
6                Abetip  20210429000176  limited_information
7                Abetip  20210429000183  limited_information
8    Abirateron Devatis  20250508000031  limited_information
9       Abirateron Teva  20201201000118  limited_information
10  Abiraterone AshCure  20231030000065  limited_information
11  Abiraterone AshCure  20231030000072  limited_information

In [ ]:
status_df["fass_status"].value_counts()

fass_status
limited_information    12
Name: count, dtype: int64

In [ ]:


OUTPUT_FILE = "fass_collection.csv"
ERROR_FILE = "fass_errors.csv"

CHECKPOINT_EVERY = 50
REQUEST_DELAY = 1

In [ ]:
def collect_product(row):

    npl_id = str(row["npl_id"])
    url = f"https://fass.se/health/product/{npl_id}/smpc"

    result = {
        "product_name": row["product_name"],
        "strength": row["strength"],
        "form": row["form"],
        "atc_code": row["atc_code"],
        "active_ingredient_simple": row["active_ingredient_simple"],
        "active_ingredient": row["active_ingredient"],
        "prescription_status": row["prescription_status"],
        "sales_status": row["sales_status"],
        "npl_id": npl_id,
        "source_url": url,

        "fass_status": None,

        "dosage": None,
        "contraindications": None,
        "warnings": None,
        "interactions": None,
        "pregnancy_breastfeeding": None,
        "side_effects": None
    }

    text = get_fass_text(npl_id)

    status = get_fass_status(text)
    result["fass_status"] = status

    if status == "smpc_available":

        for section_name, (start, end) in sections.items():

            result[section_name] = extract_section(
                text,
                start,
                end
            )

    return result

In [ ]:


if os.path.exists(OUTPUT_FILE):

    existing_df = pd.read_csv(
        OUTPUT_FILE,
        dtype={"npl_id": str}
    )

    completed_ids = set(
        existing_df["npl_id"]
        .astype(str)
        .str.replace(r"\.0$", "", regex=True)
    )

    results = existing_df.to_dict("records")

    print(
        "Resuming from previous collection:",
        len(completed_ids),
        "products already processed."
    )

else:

    completed_ids = set()
    results = []

    print("Starting new FASS collection.")



errors = []




processed_since_save = 0

for index, row in master_df.iterrows():

    npl_id = str(row["npl_id"])

    # Already collected → skip
    if npl_id in completed_ids:
        continue

    try:

        result = collect_product(row)

        results.append(result)
        completed_ids.add(npl_id)

        processed_since_save += 1

        print(
            f"[{len(completed_ids)}/{len(master_df)}]",
            row["product_name"],
            "->",
            result["fass_status"]
        )

    except Exception as e:

        errors.append({
            "product_name": row["product_name"],
            "npl_id": npl_id,
            "error": str(e)
        })

        print(
            f"[ERROR] {row['product_name']} | {npl_id}",
            str(e)
        )


    if processed_since_save >= CHECKPOINT_EVERY:

        pd.DataFrame(results).to_csv(
            OUTPUT_FILE,
            index=False,
            encoding="utf-8-sig"
        )

        if errors:
            pd.DataFrame(errors).to_csv(
                ERROR_FILE,
                index=False,
                encoding="utf-8-sig"
            )

        print(
            "\n--- CHECKPOINT SAVED:",
            len(completed_ids),
            "products ---\n"
        )

        processed_since_save = 0

    time.sleep(REQUEST_DELAY)

Starting new FASS collection.
[1/15190] Abacavir/Lamivudine Accord -> smpc_available
[2/15190] Abacavir/Lamivudine Glenmark -> smpc_available
[3/15190] Abacavir/Lamivudine Medical Valley -> smpc_available
[4/15190] Abacavir/Lamivudine Sandoz -> smpc_available
[5/15190] Abacavir/Lamivudine STADA -> smpc_available
[6/15190] Abakavir/Lamivudin Viatris -> smpc_available
[7/15190] ABASAGLAR -> smpc_available
[8/15190] ABASAGLAR KwikPen -> smpc_available
[9/15190] ABASAGLAR Tempo Pen -> smpc_available
[10/15190] Abavalex -> limited_information
[11/15190] Abavalex -> limited_information
[12/15190] Abavalex -> limited_information
[13/15190] Abavalex -> limited_information
[14/15190] Abavalex -> limited_information
[15/15190] Abbonate -> smpc_available
[16/15190] Abboticin -> smpc_available
[17/15190] Abboticin -> smpc_available
[18/15190] Abboticin Novum -> smpc_available
[19/15190] Abdomin Citrus -> limited_information
[20/15190] Abdomin Junior Neutral -> smpc_available
[21/15190] Abdomin Neutral -> smpc_available
[22/15190] Abecma -> smpc_available
[23/15190] Abecol -> smpc_available
[24/15190] Abetip -> limited_information
[25/15190] Abetip -> limited_information
[26/15190] Abevmy -> smpc_available
[27/15190] Abilify -> smpc_available
[28/15190] Abilify -> smpc_available
[29/15190] Abilify -> smpc_available
[30/15190] Abilify -> smpc_available
[31/15190] Abilify -> smpc_available
[32/15190] Abilify -> smpc_available
[33/15190] Abilify -> smpc_available
[34/15190] Abilify -> smpc_available
[35/15190] Abilify -> smpc_available
[36/15190] ABILIFY MAINTENA -> smpc_available
[37/15190] ABILIFY MAINTENA -> smpc_available
[38/15190] ABILIFY MAINTENA -> smpc_available
[39/15190] ABILIFY MAINTENA -> smpc_available
[40/15190] ABILIFY MAINTENA -> smpc_available
[41/15190] ABILIFY MAINTENA -> smpc_available
[42/15190] Abirateron Avansor -> smpc_available
[43/15190] Abirateron Devatis -> limited_information
[44/15190] Abirateron Medical Valley -> smpc_available
[45/15190] Abirateron Sandoz -> smpc_available
[46/15190] Abirateron Teva -> limited_information
[47/15190] Abiraterone Accord -> smpc_available
[48/15190] Abiraterone Accord -> smpc_available
[49/15190] Abiraterone AshCure -> limited_information
[50/15190] Abiraterone AshCure -> limited_information

--- CHECKPOINT SAVED: 50 products ---

[51/15190] Abiraterone Glenmark -> smpc_available
[52/15190] Abiraterone Krka -> smpc_available
[53/15190] Abiraterone Mylan -> smpc_available
[54/15190] Abiraterone Mylan -> smpc_available
[55/15190] Abiraterone Qilu -> smpc_available
[56/15190] Abiraterone Qilu -> smpc_available
[57/15190] Abiraterone STADA -> smpc_available
[58/15190] Abiraterone Vivanta -> limited_information
[59/15190] Abiraterone Vivanta -> limited_information
[60/15190] Abiraterone Zentiva -> smpc_available
[61/15190] Ablymico -> limited_information
[62/15190] Abraxane -> smpc_available
[63/15190] Abriff -> unknown
[64/15190] Abriff -> unknown
[65/15190] Abriff -> unknown
[66/15190] Abrysvo -> smpc_available
[67/15190] Abrysvo -> smpc_available
[68/15190] Abseamed -> limited_information
[69/15190] Abseamed -> limited_information
[70/15190] Abseamed -> limited_information
[71/15190] Abseamed -> limited_information
[72/15190] Abseamed -> limited_information
[73/15190] Abseamed -> limited_information
[74/15190] Abseamed -> limited_information
[75/15190] Abseamed -> limited_information
[76/15190] Abseamed -> limited_information
[77/15190] Abseamed -> limited_information
[78/15190] Abseamed -> limited_information
[79/15190] Abseamed -> limited_information
[80/15190] Abseamed -> limited_information
[81/15190] Absenor -> smpc_available
[82/15190] Absenor -> smpc_available
[83/15190] Absenor -> smpc_available
[84/15190] Absenor -> smpc_available
[85/15190] Absenor -> smpc_available
[86/15190] Absenor Depot -> smpc_available
[87/15190] Absenor Depot -> smpc_available
[88/15190] Abstral -> smpc_available
[89/15190] Abstral -> smpc_available
[90/15190] Abstral -> smpc_available
[91/15190] Abstral -> smpc_available
[92/15190] Abstral -> smpc_available
[93/15190] Abstral -> smpc_available
[94/15190] ACARIZAX -> smpc_available
[95/15190] Accofil -> smpc_available
[96/15190] Accofil -> smpc_available
[97/15190] Accofil -> smpc_available
[98/15190] Accofil -> smpc_available
[99/15190] Acetylcystein 1A Farma -> smpc_available
[100/15190] Acetylcystein 1A Farma -> smpc_available

--- CHECKPOINT SAVED: 100 products ---

[101/15190] Acetylcystein Alternova -> smpc_available
[102/15190] Acetylcystein Viatris -> smpc_available
[103/15190] Acetylcystein Viatris -> smpc_available
[104/15190] Acetylcysteine Macure -> limited_information
[105/15190] Acetylsalicylic acid Bluefish -> smpc_available
[106/15190] Acetylsalicylic acid Bluefish -> smpc_available
[107/15190] Acetylsalicylic acid Krka -> smpc_available
[108/15190] Acetylsalicylic acid Krka -> smpc_available
[109/15190] Acetylsalicylic acid Krka -> smpc_available
[110/15190] Acetylsalicylsyra ABECE -> smpc_available
[111/15190] Acetylsalicylsyra Evolan -> smpc_available
[112/15190] Acetylsalicylsyra G.L. Pharma -> limited_information
[113/15190] Acetylsalicylsyra G.L. Pharma -> smpc_available
[114/15190] Acetylsalicylsyra Teva -> limited_information
[115/15190] Acetylsalicylsyra Teva -> limited_information
[116/15190] Acetylsalicylsyra Teva -> smpc_available
[117/15190] Aciclovir Accord -> smpc_available
[ERROR] Aciclovir Noridem | 20240725000051 404 Client Error: Not Found for url: https://fass.se/health/product/20240725000051/smpc
[ERROR] Aciclovir Noridem | 20240725000068 404 Client Error: Not Found for url: https://fass.se/health/product/20240725000068/smpc
[118/15190] Aciclovir Orion -> smpc_available
[119/15190] Aciclovir Orion -> smpc_available
[120/15190] Aciclovir Orion -> smpc_available
[121/15190] Aciclovir Pfizer -> smpc_available
[122/15190] Aciclovir Sandoz -> smpc_available
[123/15190] Aciclovir Sandoz -> smpc_available
[124/15190] Aciclovir SUN -> smpc_available
[125/15190] Aciclovir SUN -> smpc_available
[126/15190] Aciclovir SUN -> smpc_available
[127/15190] Aciklovir ABECE -> smpc_available
[128/15190] Aciklovir STADA -> smpc_available
[129/15190] Aciklovir STADA -> smpc_available
[130/15190] Aciklovir STADA -> smpc_available
[131/15190] Acitretin Orifarm -> smpc_available
[132/15190] Acitretin Orifarm -> smpc_available
[133/15190] Aclasta -> smpc_available
[134/15190] Acnatac -> limited_information
[135/15190] Acnatac -> limited_information
[136/15190] Acnatac -> smpc_available
[137/15190] Aco Acnegel -> smpc_available
[138/15190] Aco Acnelösning -> smpc_available
[139/15190] Act-HIB -> smpc_available
[140/15190] Actelsar HCT -> limited_information
[141/15190] Actelsar HCT -> limited_information
[142/15190] Actelsar HCT -> limited_information
[143/15190] Actibon -> limited_information
[144/15190] Actibon -> limited_information
[145/15190] Actikerall -> smpc_available
[146/15190] Actilyse -> smpc_available
[147/15190] Actilyse -> smpc_available
[148/15190] Actilyse -> limited_information
[149/15190] Actilyse -> limited_information
[150/15190] Actilyse -> limited_information

--- CHECKPOINT SAVED: 150 products ---

[151/15190] Actiq -> limited_information
[152/15190] Actiq -> limited_information
[153/15190] Actiq -> limited_information
[154/15190] Actiq -> limited_information
[155/15190] Actiq -> limited_information
[156/15190] Actiq -> limited_information
[157/15190] Activelle -> smpc_available
[158/15190] Actos -> smpc_available
[159/15190] Actos -> smpc_available
[160/15190] Actos -> smpc_available
[161/15190] Actraphane 30 -> limited_information
[162/15190] Actraphane 30 -> limited_information
[163/15190] Actraphane 30 FlexPen -> limited_information
[164/15190] Actraphane 30 InnoLet -> limited_information
[165/15190] Actraphane 30 Penfill -> limited_information
[166/15190] Actraphane 50 Penfill -> limited_information
[167/15190] Actrapid -> smpc_available
[168/15190] Actrapid -> limited_information
[169/15190] Actrapid FlexPen -> limited_information
[170/15190] Actrapid InnoLet -> limited_information
[171/15190] Actrapid Penfill -> smpc_available
[172/15190] Acvybra -> limited_information
[173/15190] Adalat Oros -> smpc_available
[174/15190] Adalat Oros -> limited_information
[175/15190] Adapalen/Bensoylperoxid Adalvo -> limited_information
[176/15190] Adapalen/Bensoylperoxid Adalvo -> limited_information
[177/15190] Adapalene/Benzoyl peroxide Orifarm -> smpc_available
[178/15190] Adapalene/Benzoyl peroxide STADA -> limited_information
[179/15190] Adapalene/Benzoyl peroxide STADA -> limited_information
[180/15190] ADARTREL -> smpc_available
[181/15190] ADARTREL -> smpc_available
[182/15190] ADARTREL -> smpc_available
[183/15190] ADASUVE -> limited_information
[184/15190] ADASUVE -> limited_information
[185/15190] ADCETRIS -> smpc_available
[186/15190] ADCIRCA -> smpc_available
[187/15190] ADCIRCA -> smpc_available
[188/15190] Addaven -> smpc_available
[189/15190] Addens-Kaliumklorid B. Braun -> smpc_available
[190/15190] Addens-Kaliumklorid B. Braun -> smpc_available
[191/15190] Addens-Natriumklorid B. Braun -> smpc_available
[192/15190] Addex-Ammoniumklorid -> smpc_available
[193/15190] Addex-Kalium -> smpc_available
[194/15190] Addex-Kaliumklorid -> smpc_available
[195/15190] Addex-Magnesium -> smpc_available
[196/15190] Addex-Natriumklorid -> smpc_available
[197/15190] Addex-THAM -> smpc_available
[198/15190] Addicort -> limited_information
[199/15190] Adempas -> smpc_available
[200/15190] Adempas -> smpc_available

--- CHECKPOINT SAVED: 200 products ---

[201/15190] Adempas -> smpc_available
[202/15190] Adempas -> smpc_available
[203/15190] Adempas -> smpc_available
[204/15190] Adempas -> smpc_available
[205/15190] Adenosin Life Medical -> smpc_available
[206/15190] Adenosin Macure -> limited_information
[207/15190] ADENURIC -> smpc_available
[208/15190] ADENURIC -> smpc_available
[209/15190] Adhesa -> smpc_available
[210/15190] Adixemin -> limited_information
[211/15190] Adixemin -> limited_information
[212/15190] Adixemin -> limited_information
[213/15190] Adixemin -> limited_information
[214/15190] Adixemin -> limited_information
[215/15190] Adixemin -> limited_information
[216/15190] Adjupanrix -> limited_information
[217/15190] Adoport -> limited_information
[218/15190] Adoport -> limited_information
[219/15190] Adoport -> limited_information
[220/15190] Adoport -> limited_information
[221/15190] Adoport -> limited_information
[222/15190] Adoport -> limited_information
[223/15190] Adoport -> limited_information
[224/15190] Adoport -> limited_information
[225/15190] Adoport -> limited_information
[226/15190] Adoport -> limited_information
[227/15190] Adoport -> limited_information
[228/15190] Adoport -> limited_information
[229/15190] Adoport -> limited_information
[230/15190] Adoport -> limited_information
[231/15190] Adoport -> limited_information
[232/15190] Adoport -> limited_information
[233/15190] Adoport -> limited_information
[234/15190] Adport -> smpc_available
[235/15190] Adport -> smpc_available
[236/15190] Adport -> limited_information
[237/15190] Adport -> smpc_available
[238/15190] Adport -> smpc_available
[239/15190] Adport -> limited_information
[240/15190] Adport -> smpc_available
[241/15190] Adrenalin 2care4 -> limited_information
[242/15190] Adrenalin 2care4 -> limited_information
[243/15190] Adrenalin Aguettant -> smpc_available
[244/15190] Adrenalin Bradex -> smpc_available
[245/15190] Adrenalin Ethypharm -> smpc_available
[246/15190] Adrenalin Martindale Pharma -> smpc_available
[247/15190] Adrenalin Viatris -> smpc_available
[248/15190] ADROVANCE -> unknown
[249/15190] ADROVANCE -> unknown
[250/15190] ADSTILADRIN -> limited_information

--- CHECKPOINT SAVED: 250 products ---

[251/15190] Adtralza -> smpc_available
[252/15190] Adtralza -> smpc_available
[253/15190] Advagraf -> smpc_available
[254/15190] Advagraf -> smpc_available
[255/15190] Advagraf -> smpc_available
[256/15190] Advagraf -> smpc_available
[257/15190] ADVATE -> smpc_available
[258/15190] ADVATE -> smpc_available
[259/15190] ADVATE -> smpc_available
[260/15190] ADVATE -> smpc_available
[261/15190] ADVATE -> smpc_available
[262/15190] ADVATE -> smpc_available
[263/15190] ADVATE -> smpc_available
[264/15190] ADVATE -> smpc_available
[265/15190] ADVATE -> smpc_available
[266/15190] ADVATE -> smpc_available
[267/15190] ADYNOVI -> smpc_available
[268/15190] ADYNOVI -> smpc_available
[269/15190] ADYNOVI -> smpc_available
[270/15190] ADYNOVI -> smpc_available
[271/15190] ADYNOVI -> smpc_available
[272/15190] ADYNOVI -> smpc_available
[273/15190] ADYNOVI -> smpc_available
[274/15190] ADYNOVI -> smpc_available
[275/15190] ADZYNMA -> smpc_available
[276/15190] ADZYNMA -> smpc_available
[277/15190] Aerinaze -> smpc_available
[ERROR] Aerion Easyhaler | 20170410000090 404 Client Error: Not Found for url: https://fass.se/health/product/20170410000090/smpc
[ERROR] Aerion Easyhaler | 20170410000106 404 Client Error: Not Found for url: https://fass.se/health/product/20170410000106/smpc
[278/15190] Aerius -> smpc_available
[279/15190] Aerius -> smpc_available
[280/15190] AeroBec -> smpc_available
[281/15190] AeroBec -> limited_information
[282/15190] AeroBec Autohaler -> limited_information
[283/15190] AeroBec Autohaler -> smpc_available
[284/15190] AeroBec Autohaler -> smpc_available
[285/15190] Aethoxysklerol -> smpc_available
[286/15190] Aethoxysklerol -> smpc_available
[287/15190] Aethoxysklerol -> smpc_available
[288/15190] Afatinib Lotus -> limited_information
[289/15190] Afatinib Lotus -> limited_information
[290/15190] Afatinib Lotus -> limited_information
[291/15190] Afatinib Lotus -> limited_information
[292/15190] Affenid -> smpc_available
[293/15190] Affenid -> smpc_available
[294/15190] Affenid -> smpc_available
[295/15190] Affenid -> smpc_available
[296/15190] Affenid -> smpc_available
[297/15190] Afinitor -> smpc_available
[298/15190] Afinitor -> smpc_available
[299/15190] Afinitor -> smpc_available
[300/15190] Afiveg -> limited_information

--- CHECKPOINT SAVED: 300 products ---

[301/15190] Afiveg -> limited_information
[302/15190] AFLUNOV -> limited_information
[303/15190] Aforbe -> smpc_available
[304/15190] Aforbe -> smpc_available
[305/15190] Afqlir -> limited_information
[306/15190] Afqlir -> smpc_available
[307/15190] AFSTYLA -> smpc_available
[308/15190] AFSTYLA -> smpc_available
[309/15190] AFSTYLA -> smpc_available
[310/15190] AFSTYLA -> smpc_available
[311/15190] AFSTYLA -> smpc_available
[312/15190] AFSTYLA -> smpc_available
[313/15190] AFSTYLA -> smpc_available
[314/15190] AGAMREE -> smpc_available
[315/15190] Aggrastat -> smpc_available
[316/15190] Aggrastat -> smpc_available
[317/15190] Agilus -> smpc_available
[318/15190] Aglira -> limited_information
[319/15190] Agomelatin Glenmark -> smpc_available
[320/15190] Agomelatine STADA -> smpc_available
[321/15190] Agomelatine Viatris -> smpc_available
[322/15190] Ahzantive -> limited_information
[323/15190] Ahzantive -> limited_information
[324/15190] Aimovig -> smpc_available
[325/15190] Aimovig -> smpc_available
[326/15190] Aimovig -> smpc_available
[327/15190] Aimovig -> smpc_available
[328/15190] Aiqlara -> limited_information
[329/15190] Airapy -> smpc_available
[330/15190] Airbufo Forspiro -> unknown
[331/15190] Airbufo Forspiro -> unknown
[332/15190] Airflusal Forspiro -> limited_information
[333/15190] Airflusal Forspiro -> limited_information
[334/15190] Airflusal Forspiro -> limited_information
[335/15190] Airflusal Forspiro -> smpc_available
[336/15190] Airflusal Forspiro -> limited_information
[337/15190] Airflusal Forspiro -> limited_information
[338/15190] Airflusal Forspiro -> limited_information
[339/15190] Airflusal Forspiro -> limited_information
[340/15190] Airflusal Forspiro -> smpc_available
[341/15190] Airomir -> smpc_available
[342/15190] Airomir -> smpc_available
[343/15190] Airomir -> smpc_available
[344/15190] Airomir Autohaler -> smpc_available
[345/15190] Airsalb -> smpc_available
[346/15190] Aitgrys -> smpc_available
[347/15190] Aitgrys -> smpc_available
[348/15190] Aitmyte -> smpc_available
[349/15190] Aitmyte -> smpc_available
[350/15190] Aitmyte -> smpc_available

--- CHECKPOINT SAVED: 350 products ---

[351/15190] AJOVY -> smpc_available
[352/15190] AJOVY -> smpc_available
[353/15190] Akamprosat Viatris -> smpc_available
[354/15190] AKANTIOR -> smpc_available
[355/15190] Akeega -> smpc_available
[356/15190] Akeega -> smpc_available
[357/15190] Akineton -> smpc_available
[358/15190] Akineton -> smpc_available
[359/15190] Aklief -> smpc_available
[360/15190] Akynzeo -> smpc_available
[361/15190] Akynzeo -> smpc_available
[362/15190] Akynzeo -> smpc_available
[363/15190] Akynzeo -> smpc_available
[364/15190] Alacare -> limited_information
[365/15190] Albumin Baxalta -> smpc_available
[366/15190] Albumin Baxalta -> smpc_available
[367/15190] Albumin Behring -> smpc_available
[368/15190] Albumin Octapharma -> limited_information
[369/15190] Albumin Octapharma -> limited_information
[370/15190] Albunorm -> smpc_available
[371/15190] Albunorm -> smpc_available
[372/15190] Albunorm -> smpc_available
[373/15190] Albunorm -> smpc_available
[374/15190] Alburex -> smpc_available
[375/15190] Alburex -> smpc_available
[376/15190] Albutein -> smpc_available
[377/15190] Albutein -> smpc_available
[378/15190] Alcosanal -> smpc_available
[379/15190] ALDARA -> smpc_available
[380/15190] Aldurazyme -> smpc_available
[381/15190] Alecensa -> smpc_available
[382/15190] Alendronat Abacus Medicine Veckotablett -> limited_information
[383/15190] Alendronat Aurobindo Veckotablett -> smpc_available
[384/15190] Alendronat Bluefish Veckotablett -> smpc_available
[385/15190] Alendronat Ebb Veckotablett -> limited_information
[386/15190] Alendronat Sandoz Veckotablett -> smpc_available
[387/15190] Alendronat STADA -> smpc_available
[388/15190] Alendronat STADA Veckotablett -> smpc_available
[389/15190] Alendronat Teva Veckotablett -> smpc_available
[390/15190] Alendronat Viatris Veckotablett -> smpc_available
[391/15190] Alensol -> limited_information
[392/15190] Alfacalcidol Strides -> limited_information
[393/15190] Alfacalcidol Strides -> limited_information
[394/15190] Alfacalcidol Strides -> limited_information
[395/15190] Alfadil -> smpc_available
[396/15190] Alfadil -> limited_information
[397/15190] Alfadil -> smpc_available
[398/15190] Alfadil BPH -> smpc_available
[399/15190] Alfadil BPH -> limited_information
[400/15190] Alfadil BPH -> smpc_available

--- CHECKPOINT SAVED: 400 products ---

[401/15190] Alfastrin -> limited_information
[402/15190] Alfastrin -> limited_information
[403/15190] Alfastrin -> limited_information
[404/15190] Alfentanil Hameln -> smpc_available
[405/15190] Alfentanil Kalceks -> smpc_available
[406/15190] Alfuzosin Orion -> smpc_available
[407/15190] Alfuzosin Orion -> smpc_available
[408/15190] Alfuzosin Rivopharm -> smpc_available
[409/15190] Alfuzosin Sandoz -> smpc_available
[410/15190] Alfuzosin STADA -> smpc_available
[411/15190] Alfuzosin STADA -> limited_information
[412/15190] Alfuzosin Teva -> smpc_available
[413/15190] Alfuzosin Viatris -> smpc_available
[414/15190] Alganex -> smpc_available
[415/15190] Algovil -> limited_information
[416/15190] Alhemo -> smpc_available
[417/15190] Alhemo -> smpc_available
[418/15190] Alhemo -> smpc_available
[419/15190] Alhemo -> smpc_available
[420/15190] Alimemazin Evolan -> smpc_available
[421/15190] Alimemazin Evolan -> smpc_available
[422/15190] Alimemazin Orifarm -> smpc_available
[423/15190] ALIMTA -> smpc_available
[424/15190] ALIMTA -> smpc_available
[425/15190] Alitretinoin 2care4 -> limited_information
[426/15190] Alitretinoin 2care4 -> limited_information
[427/15190] Alitretinoin 2care4 -> limited_information
[428/15190] Alitretinoin 2care4 -> limited_information
[429/15190] Alitretinoin 2care4 -> limited_information
[430/15190] Alitretinoin 2care4 -> limited_information
[431/15190] Alitretinoin 2care4 -> limited_information

In [ ]:
fass_all = pd.read_csv(
    "fass_collection.csv",
    dtype={"npl_id": str}
)

print("Collected rows:", len(fass_all))
print(fass_all["fass_status"].value_counts())

Collected rows: 14900
fass_status
smpc_available         9459
limited_information    5150
unknown                 291
Name: count, dtype: int64